name: Checkout and download build ⚙️
description: Checkout the project and download the build artifacts from a previous step.

runs:
  using: composite
  steps:
    - name: Checkout Repo
        uses: actions/checkout@master
    - name: Install Dependencies
        run: npm ci --force
    - name: Download Artifact
        uses: actions/download-artifact@master
        with:
            name: build
            path: build
