name: Install dependencies and download build ⚙️
description: Install dependencies and download build

runs:
  using: composite
  steps:
    - name: Install Dependencies
        run: npm ci --force
    - name: Download Artifact
        uses: actions/download-artifact@master
        with:
            name: build
            path: build
